---
title: "06.1_results_ALL"
author: "Meridith L Bartley"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load covariates, data, etc  
  load(file = "../rdata-data/extrap_full") #created in 04.1
  load(file = "../rdata-data/list-into-extrap.Rdata") #created in 04.1
  list2env(savelist,globalenv())
  load(file = "../rdata-data/extrap_values_20180927") #created in 06.1

load(file = "../rdata-data/extrap_full") #created in 04.1
load(file = "../rdata-data/extrap_TNonly.Rdata") #created in 04.2



```

```{r extrapolations - how many}
cutoffs_MVt_howmany <- vector()
cutoffs_MVd_howmany <- vector()
cutoffs_UV_howmany <- vector()

unSampled_TN <- which(is.na(Y$tn_combined))

for (i in 1:length(cutoffs.cond$cond.extrap)){
  cutoffs_MVt_howmany[i] <- sum(na.omit(LAGOS_extrapolate$extrapolate[[i]][1, - Sampled ]==0)) #only in/out but same identified as numeric 
  cutoffs_MVd_howmany[i] <- sum(na.omit(LAGOS_extrapolate$extrapolate[[i]][2, - Sampled ]==0))
  cutoffs_UV_howmany[i] <- sum(na.omit(cutoffs.cond$cond.extrap[[i]][1, unSampled_TN ]==0))
}

cutoffs_MVt_howmany 
cutoffs_MVd_howmany

cutoffs_UV_howmany
  
```

```{r extrapolations - which lakes?}
cutoffs_MVt_where <- vector()
cutoffs_MVd_where <- vector()
cutoffs_UV_where <- vector()

  
  

  ##bring Lake IDs forward
  extrap_id_x_y <-  cbind(gg_dat[[1]], #extrapolation info
                    lakeID, #lake id
                    X, 
                    Y) #logY 
  
  whichID.extrap <- list()
  names<- colnames(extrap_id_x_y)[c(3,4,9,10,15,16,21,22)] 
  
  for(n in names) {
    extrapolated.all <- which(factor(extrap_id_x_y[,n]) == 0)
  extrapolated.pred <- extrapolated.all[which(extrapolated.all > max(Sampled))]
  
  whichID.extrap[[n]] <- extrap_id_x_y$lakeID[extrapolated.pred]
  }

  
  
  
```
